//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear All.
        /// </summary>
        public static string _ClearAll {
            get {
                return ResourceManager.GetString("_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear Analyzed Result.
        /// </summary>
        public static string _ClearAnalyzedResult {
            get {
                return ResourceManager.GetString("_ClearAnalyzedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string _Export {
            get {
                return ResourceManager.GetString("_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string _ExportEtc {
            get {
                return ResourceManager.GetString("_ExportEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string _OpenEtc {
            get {
                return ResourceManager.GetString("_OpenEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Option.
        /// </summary>
        public static string _Option {
            get {
                return ResourceManager.GetString("_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string _Quit {
            get {
                return ResourceManager.GetString("_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Range.
        /// </summary>
        public static string _Range {
            get {
                return ResourceManager.GetString("_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Bookmarks.
        /// </summary>
        public static string _ResetBookmarks {
            get {
                return ResourceManager.GetString("_ResetBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Color Filters.
        /// </summary>
        public static string _ResetColorFilters {
            get {
                return ResourceManager.GetString("_ResetColorFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Comments.
        /// </summary>
        public static string _ResetComments {
            get {
                return ResourceManager.GetString("_ResetComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Filters.
        /// </summary>
        public static string _ResetFilters {
            get {
                return ResourceManager.GetString("_ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set Keyword.
        /// </summary>
        public static string _SetKeyword {
            get {
                return ResourceManager.GetString("_SetKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set Log Parameter.
        /// </summary>
        public static string _SetLogParameter {
            get {
                return ResourceManager.GetString("_SetLogParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set parameter.
        /// </summary>
        public static string _SetParameter {
            get {
                return ResourceManager.GetString("_SetParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pattern Item.
        /// </summary>
        public static string AddPatternItem {
            get {
                return ResourceManager.GetString("AddPatternItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackGround Color.
        /// </summary>
        public static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file..
        /// </summary>
        public static string CAN_NOT_CREATE_FILE {
            get {
                return ResourceManager.GetString("CAN_NOT_CREATE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS.
        /// </summary>
        public static string CCS {
            get {
                return ResourceManager.GetString("CCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CCS Log File.
        /// </summary>
        public static string CCSLogFile {
            get {
                return ResourceManager.GetString("CCSLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CCS Memo Log File.
        /// </summary>
        public static string CCSMemoLogFile {
            get {
                return ResourceManager.GetString("CCSMemoLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new file.
        /// </summary>
        public static string ConfirmMergeFileCaption {
            get {
                return ResourceManager.GetString("ConfirmMergeFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to merge the new file to the current file(s)?.
        /// </summary>
        public static string ConfirmMergeFileMessage {
            get {
                return ResourceManager.GetString("ConfirmMergeFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Parameters.
        /// </summary>
        public static string CounterParameter {
            get {
                return ResourceManager.GetString("CounterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXDI.
        /// </summary>
        public static string CXDI {
            get {
                return ResourceManager.GetString("CXDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CXDI Log File.
        /// </summary>
        public static string CXDILogFile {
            get {
                return ResourceManager.GetString("CXDILogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CXDI Memo Log File.
        /// </summary>
        public static string CXDIMemoLogFile {
            get {
                return ResourceManager.GetString("CXDIMemoLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data value is not supported.
        /// </summary>
        public static string DATA_VALUE_NOT_SUPPORTED_EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("DATA_VALUE_NOT_SUPPORTED_EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must not be empty.
        /// </summary>
        public static string DATE_DISPLAY_TEXT {
            get {
                return ResourceManager.GetString("DATE_DISPLAY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DateColon {
            get {
                return ResourceManager.GetString("DateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time &apos;.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Range: &quot;To&quot; value must be greater than &quot;From&quot; value.
        /// </summary>
        public static string DateTimeToGreaterThanFromValueErrorMessage {
            get {
                return ResourceManager.GetString("DateTimeToGreaterThanFromValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword is duplicate..
        /// </summary>
        public static string DuplicateKeywordErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateKeywordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword and Log item are duplicate.
        /// </summary>
        public static string DuplicateKeywordWithLogItemErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateKeywordWithLogItemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is duplicate..
        /// </summary>
        public static string DuplicateNameErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pattern.
        /// </summary>
        public static string EditPatternItem {
            get {
                return ResourceManager.GetString("EditPatternItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Action.
        /// </summary>
        public static string ErrorAction {
            get {
                return ResourceManager.GetString("ErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Recipe.
        /// </summary>
        public static string ErrorRecipe {
            get {
                return ResourceManager.GetString("ErrorRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file {0} because it is being used by another process. Please change the file name for export..
        /// </summary>
        public static string EXPORT_FAILURE {
            get {
                return ResourceManager.GetString("EXPORT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string Exporting3Dot {
            get {
                return ResourceManager.GetString("Exporting3Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string FILE_LOG_LOAD_CAPTION {
            get {
                return ResourceManager.GetString("FILE_LOG_LOAD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}..
        /// </summary>
        public static string FILE_LOG_LOAD_EXCEPTION {
            get {
                return ResourceManager.GetString("FILE_LOG_LOAD_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extension.
        /// </summary>
        public static string FILE_LOG_LOAD_INVALID_EXTENSION {
            get {
                return ResourceManager.GetString("FILE_LOG_LOAD_INVALID_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when writing to file: {0}..
        /// </summary>
        public static string FILE_WRITE_EXCEPTION {
            get {
                return ResourceManager.GetString("FILE_WRITE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string FilterColon {
            get {
                return ResourceManager.GetString("FilterColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name:.
        /// </summary>
        public static string FilterNameColon {
            get {
                return ResourceManager.GetString("FilterNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Setting.
        /// </summary>
        public static string FilterSetting {
            get {
                return ResourceManager.GetString("FilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter String:.
        /// </summary>
        public static string FilterStringColon {
            get {
                return ResourceManager.GetString("FilterStringColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewmodel is not referenced by any registered View..
        /// </summary>
        public static string FIND_OWNER_WINDOW_ARGUMENT_EXCEPTION {
            get {
                return ResourceManager.GetString("FIND_OWNER_WINDOW_ARGUMENT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View is not contained within a Window..
        /// </summary>
        public static string FIND_OWNER_WINDOW_INVALID_OPERATION_EXCEPTION {
            get {
                return ResourceManager.GetString("FIND_OWNER_WINDOW_INVALID_OPERATION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Y Range: &quot;To&quot; value must be greater than &quot;From&quot; value.
        /// </summary>
        public static string FirstYToGreaterThanFromValueErrorMessage {
            get {
                return ResourceManager.GetString("FirstYToGreaterThanFromValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Mode.
        /// </summary>
        public static string FollowMode {
            get {
                return ResourceManager.GetString("FollowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForeGround Color.
        /// </summary>
        public static string ForeGroundColor {
            get {
                return ResourceManager.GetString("ForeGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export..
        /// </summary>
        public static string GRAPH_EXPORT_NO_DATA {
            get {
                return ResourceManager.GetString("GRAPH_EXPORT_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Param Setting.
        /// </summary>
        public static string GraphParamSetting {
            get {
                return ResourceManager.GetString("GraphParamSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Keyword:.
        /// </summary>
        public static string InputKeywordColon {
            get {
                return ResourceManager.GetString("InputKeywordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to.
        /// </summary>
        public static string JumpTo {
            get {
                return ResourceManager.GetString("JumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword:.
        /// </summary>
        public static string KeywordColon {
            get {
                return ResourceManager.GetString("KeywordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Count.
        /// </summary>
        public static string KeywordCount {
            get {
                return ResourceManager.GetString("KeywordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Count Setting.
        /// </summary>
        public static string KeywordCountSetting {
            get {
                return ResourceManager.GetString("KeywordCountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line .
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment....
        /// </summary>
        public static string Loading_Summary {
            get {
                return ResourceManager.GetString("Loading_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading_Window_Title {
            get {
                return ResourceManager.GetString("Loading_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        public static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Display Setting.
        /// </summary>
        public static string LogDisplaySetting {
            get {
                return ResourceManager.GetString("LogDisplaySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Id.
        /// </summary>
        public static string LogId {
            get {
                return ResourceManager.GetString("LogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Item.
        /// </summary>
        public static string LogItem {
            get {
                return ResourceManager.GetString("LogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Item:.
        /// </summary>
        public static string LogItemColon {
            get {
                return ResourceManager.GetString("LogItemColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log item must not be empty..
        /// </summary>
        public static string LogItemNotEmptyErrorMessage {
            get {
                return ResourceManager.GetString("LogItemNotEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS.
        /// </summary>
        public static string LogKindTarget_CCS {
            get {
                return ResourceManager.GetString("LogKindTarget_CCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS and CXDI.
        /// </summary>
        public static string LogKindTarget_CCS_CXDI {
            get {
                return ResourceManager.GetString("LogKindTarget_CCS_CXDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXDI.
        /// </summary>
        public static string LogKindTarget_CXDI {
            get {
                return ResourceManager.GetString("LogKindTarget_CXDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        public static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type:.
        /// </summary>
        public static string LogTypeColon {
            get {
                return ResourceManager.GetString("LogTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum date must be greater than Minimum date.
        /// </summary>
        public static string MAXIMUM_DATE_EXCEPTION {
            get {
                return ResourceManager.GetString("MAXIMUM_DATE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum filter item..
        /// </summary>
        public static string MaximumFilterItemErrorMessage {
            get {
                return ResourceManager.GetString("MaximumFilterItemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Memo....
        /// </summary>
        public static string MEMO_EXPORT_CAPTION {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MEMO_EXPORT_EXIST_FILE_CAPTION {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_EXIST_FILE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Do you want to overwrite?.
        /// </summary>
        public static string MEMO_EXPORT_EXIST_FILE_TEXT {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_EXIST_FILE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log record to export..
        /// </summary>
        public static string MEMO_EXPORT_NO_RECORD {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_NO_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when writing to file: {0}..
        /// </summary>
        public static string MEMO_EXPORT_TEXT_EXCEPTION {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_TEXT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Successfully.
        /// </summary>
        public static string MEMO_EXPORT_TEXT_SUCCESS {
            get {
                return ResourceManager.GetString("MEMO_EXPORT_TEXT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MEMO_IMPORT_CAPTION {
            get {
                return ResourceManager.GetString("MEMO_IMPORT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}..
        /// </summary>
        public static string MEMO_IMPORT_TEXT_EXCEPTION {
            get {
                return ResourceManager.GetString("MEMO_IMPORT_TEXT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string MessageConfirm {
            get {
                return ResourceManager.GetString("MessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already loaded..
        /// </summary>
        public static string MessageFileAlreadyLoad {
            get {
                return ResourceManager.GetString("MessageFileAlreadyLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Line.
        /// </summary>
        public static string MoveToLine {
            get {
                return ResourceManager.GetString("MoveToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Time.
        /// </summary>
        public static string MoveToTime {
            get {
                return ResourceManager.GetString("MoveToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: .
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records exported.
        /// </summary>
        public static string NO_RECORD_EXPORTED {
            get {
                return ResourceManager.GetString("NO_RECORD_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect file format..
        /// </summary>
        public static string NOT_DETECT_FORMAT_FILE_EXCEPTION {
            get {
                return ResourceManager.GetString("NOT_DETECT_FORMAT_FILE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read file:.
        /// </summary>
        public static string NOT_READ_FILE_EXCEPTION {
            get {
                return ResourceManager.GetString("NOT_READ_FILE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not displayed in log view..
        /// </summary>
        public static string NotDisplayLogViewMessage {
            get {
                return ResourceManager.GetString("NotDisplayLogViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; is not displayed in log view..
        /// </summary>
        public static string NotDisplayLogViewWithDateTimeMessage {
            get {
                return ResourceManager.GetString("NotDisplayLogViewWithDateTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest: .
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Analyzed.
        /// </summary>
        public static string PatternAnalyzed {
            get {
                return ResourceManager.GetString("PatternAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid number or fraction.
        /// </summary>
        public static string PleaseInputAValidDecimalNumberOrAValidFraction {
            get {
                return ResourceManager.GetString("PleaseInputAValidDecimalNumberOrAValidFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input filter string.
        /// </summary>
        public static string PleaseInputFilterString {
            get {
                return ResourceManager.GetString("PleaseInputFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input number greater or equal 0.
        /// </summary>
        public static string PleaseInputNumberValueGreaterOrEqual0 {
            get {
                return ResourceManager.GetString("PleaseInputNumberValueGreaterOrEqual0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Time:.
        /// </summary>
        public static string ProcessTimeColon {
            get {
                return ResourceManager.GetString("ProcessTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_DISPLAY_SETTING_FILE_NOT_FOUND_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_DISPLAY_SETTING_FILE_NOT_FOUND_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_FILTER_SETTING_FILE_NOT_FOUND_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_FILTER_SETTING_FILE_NOT_FOUND_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_FILTER_SETTING_OTHER_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_FILTER_SETTING_OTHER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_KEYWORD_COUNT_SETTING_FILE_NOT_FOUND_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_KEYWORD_COUNT_SETTING_FILE_NOT_FOUND_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_KEYWORD_COUNT_SETTING_OTHER_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_KEYWORD_COUNT_SETTING_OTHER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_PATTERN_SETTING_FILE_NOT_FOUND_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_PATTERN_SETTING_FILE_NOT_FOUND_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when reading file: {0}.
        /// </summary>
        public static string READ_PATTERN_SETTING_OTHER_EXCEPTION {
            get {
                return ResourceManager.GetString("READ_PATTERN_SETTING_OTHER_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string ResultColon {
            get {
                return ResourceManager.GetString("ResultColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Keyword:.
        /// </summary>
        public static string RootKeywordColon {
            get {
                return ResourceManager.GetString("RootKeywordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Parameters.
        /// </summary>
        public static string SaveParameter {
            get {
                return ResourceManager.GetString("SaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Y Range: &quot;To&quot; value must be greater than &quot;From&quot; value.
        /// </summary>
        public static string SecondYToGreaterThanFromValueErrorMessage {
            get {
                return ResourceManager.GetString("SecondYToGreaterThanFromValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one element for each log type.
        /// </summary>
        public static string SelectLogKindErrorMessage {
            get {
                return ResourceManager.GetString("SelectLogKindErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string ShowGrid {
            get {
                return ResourceManager.GetString("ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        public static string ThreadId {
            get {
                return ResourceManager.GetString("ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string TimeColon {
            get {
                return ResourceManager.GetString("TimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Condition:.
        /// </summary>
        public static string TimeConditionColon {
            get {
                return ResourceManager.GetString("TimeConditionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS Filter Settting.
        /// </summary>
        public static string TitleCCSFilterSetting {
            get {
                return ResourceManager.GetString("TitleCCSFilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS Keyword Count Setting.
        /// </summary>
        public static string TitleCCSKeywordCountSetting {
            get {
                return ResourceManager.GetString("TitleCCSKeywordCountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS Pattern Manager.
        /// </summary>
        public static string TitleCCSPatternManager {
            get {
                return ResourceManager.GetString("TitleCCSPatternManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXDI Filter Setting.
        /// </summary>
        public static string TitleCXDIFilterSetting {
            get {
                return ResourceManager.GetString("TitleCXDIFilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXDI Keyword Count Setting.
        /// </summary>
        public static string TitleCXDIKeywordCountSetting {
            get {
                return ResourceManager.GetString("TitleCXDIKeywordCountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXDI Pattern Manager.
        /// </summary>
        public static string TitleCXDIPatternManager {
            get {
                return ResourceManager.GetString("TitleCXDIPatternManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _To CSV.
        /// </summary>
        public static string ToCSV {
            get {
                return ResourceManager.GetString("ToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _To image.
        /// </summary>
        public static string ToImage {
            get {
                return ResourceManager.GetString("ToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt.
        /// </summary>
        public static string TXT {
            get {
                return ResourceManager.GetString("TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Action.
        /// </summary>
        public static string UserAction {
            get {
                return ResourceManager.GetString("UserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be empty.
        /// </summary>
        public static string ValidateEmptyNameMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Keyword must not be empty.
        /// </summary>
        public static string ValidateEmptyRootKeyMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyRootKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of String must not be empty.
        /// </summary>
        public static string ValidateEmptyStringListMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyStringListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must not be empty.
        /// </summary>
        public static string ValidateEmptyStringMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must not be empty.
        /// </summary>
        public static string ValidateEmptyStringObjectMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyStringObjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must not be empty.
        /// </summary>
        public static string ValidateEmptyStringValueMessage {
            get {
                return ResourceManager.GetString("ValidateEmptyStringValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of Keyword is 50 characters.
        /// </summary>
        public static string ValidateLengthKeywordMessage {
            get {
                return ResourceManager.GetString("ValidateLengthKeywordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of Name is 50 characters.
        /// </summary>
        public static string ValidateLengthNameMessage {
            get {
                return ResourceManager.GetString("ValidateLengthNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of Root Keyword is 50 characters.
        /// </summary>
        public static string ValidateLengthRootKeyMessage {
            get {
                return ResourceManager.GetString("ValidateLengthRootKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of Object is 50 characters.
        /// </summary>
        public static string ValidateLengthStringObjectMessage {
            get {
                return ResourceManager.GetString("ValidateLengthStringObjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of String is 50 characters.
        /// </summary>
        public static string ValidateLengthStringValueMessage {
            get {
                return ResourceManager.GetString("ValidateLengthStringValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can enable upto 2 parameters.
        /// </summary>
        public static string ValidateMaximumEnableParameter {
            get {
                return ResourceManager.GetString("ValidateMaximumEnableParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can filter upto 5 keywords.
        /// </summary>
        public static string ValidateMaxKeywordCountMessage {
            get {
                return ResourceManager.GetString("ValidateMaxKeywordCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can register upto 10 items.
        /// </summary>
        public static string ValidateMaxRegisterItemMessage {
            get {
                return ResourceManager.GetString("ValidateMaxRegisterItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string ValidateUniqueNameMessage {
            get {
                return ResourceManager.GetString("ValidateUniqueNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be unique.
        /// </summary>
        public static string ValidateUniqueStringValueMessage {
            get {
                return ResourceManager.GetString("ValidateUniqueStringValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
